UPDATE verses SET bName = 'Genesis' where bookID = 1;
UPDATE verses SET bName = 'Exodus' where bookID = 2;
UPDATE verses SET bName = 'Leviticus' where bookID = 3;
UPDATE verses SET bName = 'Numbers' where bookID = 4;
UPDATE verses SET bName = 'Deuteronomy' where bookID = 5;
UPDATE verses SET bName = 'Joshua' where bookID = 6;
UPDATE verses SET bName = 'Judges' where bookID = 7;
UPDATE verses SET bName = 'Ruth' where bookID = 8;
UPDATE verses SET bName = '1 Samuel' where bookID = 9;
UPDATE verses SET bName = '2 Samuel' where bookID = 10;
UPDATE verses SET bName = '1 Kings' where bookID = 11;
UPDATE verses SET bName = '2 Kings' where bookID = 12;
UPDATE verses SET bName = '1 Chronicles' where bookID = 13;
UPDATE verses SET bName = '2 Chronicles' where bookID = 14;
UPDATE verses SET bName = 'Ezra' where bookID = 15;
UPDATE verses SET bName = 'Nehemiah' where bookID = 16;
UPDATE verses SET bName = 'Esther' where bookID = 17;
UPDATE verses SET bName = 'Job' where bookID = 18;
UPDATE verses SET bName = 'Psalms' where bookID = 19;
UPDATE verses SET bName = 'Proverbs' where bookID = 20;
UPDATE verses SET bName = 'Ecclesiastes' where bookID = 21;
UPDATE verses SET bName = 'Song of Songs' where bookID = 22;
UPDATE verses SET bName = 'Isaiah' where bookID = 23;
UPDATE verses SET bName = 'Jeremiah' where bookID = 24;
UPDATE verses SET bName = 'Lamentations' where bookID = 25;
UPDATE verses SET bName = 'Ezekiel' where bookID = 26;
UPDATE verses SET bName = 'Daniel' where bookID = 27;
UPDATE verses SET bName = 'Hosea' where bookID = 28;
UPDATE verses SET bName = 'Joel' where bookID = 29;
UPDATE verses SET bName = 'Amos' where bookID = 30;
UPDATE verses SET bName = 'Obadiah' where bookID = 31;
UPDATE verses SET bName = 'Jonah' where bookID = 32;
UPDATE verses SET bName = 'Micah' where bookID = 33;
UPDATE verses SET bName = 'Nahum' where bookID = 34;
UPDATE verses SET bName = 'Habakkuk' where bookID = 35;
UPDATE verses SET bName = 'Zephaniah' where bookID = 36;
UPDATE verses SET bName = 'Haggai' where bookID = 37;
UPDATE verses SET bName = 'Zechariah' where bookID = 38;
UPDATE verses SET bName = 'Malachi' where bookID = 39;
UPDATE verses SET bName = 'Matthew' where bookID = 40;
UPDATE verses SET bName = 'Mark' where bookID = 41;
UPDATE verses SET bName = 'Luke' where bookID = 42;
UPDATE verses SET bName = 'John' where bookID = 43;
UPDATE verses SET bName = 'Acts' where bookID = 44;
UPDATE verses SET bName = 'Romans' where bookID = 45;
UPDATE verses SET bName = '1 Corinthians' where bookID = 46;
UPDATE verses SET bName = '2 Corinthians' where bookID = 47;
UPDATE verses SET bName = 'Galatians' where bookID = 48;
UPDATE verses SET bName = 'Ephesians' where bookID = 49;
UPDATE verses SET bName = 'Philippians' where bookID = 50;
UPDATE verses SET bName = 'Colossians' where bookID = 51;
UPDATE verses SET bName = '1 Thessalonians' where bookID = 52;
UPDATE verses SET bName = '2 Thessalonians' where bookID = 53;
UPDATE verses SET bName = '1 Timothy' where bookID = 54;
UPDATE verses SET bName = '2 Timothy' where bookID = 55;
UPDATE verses SET bName = 'Titus' where bookID = 56;
UPDATE verses SET bName = 'Philemon' where bookID = 57;
UPDATE verses SET bName = 'Hebrews' where bookID = 58;
UPDATE verses SET bName = 'James' where bookID = 59;
UPDATE verses SET bName = '1 Peter' where bookID = 60;
UPDATE verses SET bName = '2 Peter' where bookID = 61;
UPDATE verses SET bName = '1 John' where bookID = 62;
UPDATE verses SET bName = '2 John' where bookID = 63;
UPDATE verses SET bName = '3 John' where bookID = 64;
UPDATE verses SET bName = 'Jude' where bookID = 65;
UPDATE verses SET bName = 'Revelation' where bookID = 66;